<?php

/**
 * PluginsfAlohaContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfAlohaContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfAlohaContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfAlohaContent');
    }
}