<?php

/**
 * PluginAlohaContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAlohaContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAlohaContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAlohaContent');
    }
}